### ISSUE TITLE
Rock Paper Scissors: Cross-Platform Playability Issue

### ISSUE THREAD

**Issue by Qoyyuum** [DipanshKhandelwal/Unique-Python#27]
Just tested out Rock Paper Scissors.

On WSL
```
$ python PythonRockPaperScissorGame/rockpaperscissorgame.py
Rock(r) , Paper (p) or Scissors (s) s
Traceback (most recent call last):
  File "PythonRockPaperScissorGame/rockpaperscissorgame.py", line 35, in <module>
    player = input("Rock(r) , Paper (p) or Scissors (s) ")
  File "<string>", line 1, in <module>
NameError: name 's' is not defined

$ python PythonRockPaperScissorGame/rockpaperscissorgame.py
Rock(r) , Paper (p) or Scissors (s) p
Traceback (most recent call last):
  File "PythonRockPaperScissorGame/rockpaperscissorgame.py", line 35, in <module>
    player = input("Rock(r) , Paper (p) or Scissors (s) ")
  File "<string>", line 1, in <module>
NameError: name 'p' is not defined

$ python PythonRockPaperScissorGame/rockpaperscissorgame.py
Rock(r) , Paper (p) or Scissors (s) r
Traceback (most recent call last):
  File "PythonRockPaperScissorGame/rockpaperscissorgame.py", line 36, in <module>
    player.lower()
AttributeError: 'module' object has no attribute 'lower'
```

On Windows:
```
PS D:\MS1\Documents\Unique-Python> python .\PythonRockPaperScissorGame\rockpaperscissorgame.py
Rock(r) , Paper (p) or Scissors (s) r
O  VS  8<
Player Wins
PS D:\MS1\Documents\Unique-Python> python .\PythonRockPaperScissorGame\rockpaperscissorgame.py
Rock(r) , Paper (p) or Scissors (s) p
|  VS  8<
Computer Wins
PS D:\MS1\Documents\Unique-Python> python .\PythonRockPaperScissorGame\rockpaperscissorgame.py
Rock(r) , Paper (p) or Scissors (s) s
8<  VS  O
Computer Wins
```

Not exactly cross-platform playable.

**Comment by DipanshKhandelwal** [comment]
Try python3
